import patientPic from "../../../../../OPD/assets/Images/DoctorProfile.jpg";
export const todaysAppointmentData = [
  {
    "#": patientPic,
    "Patient Name": "John Doe",
    Gender: "Male",
    "Last Visit": "27/4/2022",
    Diseases: "fever",
    Report: "<PictureAsPdfOutlinedIcon />",
    Details: "",
  },
  {
    "#": patientPic,
    "Patient Name": "John Doe",
    Gender: "Male",
    "Last Visit": "27/4/2022",
    Diseases: "cholera",
    Report: "<PictureAsPdfOutlinedIcon />",
    Details: "",
  },
  {
    "#": patientPic,
    "Patient Name": "John Doe",
    Gender: "Male",
    "Last Visit": "27/4/2022",
    Diseases: "jaundice",
    Report: "<PictureAsPdfOutlinedIcon />",
    Details: "",
  },
  {
    "#": patientPic,
    "Patient Name": "John Doe",
    Gender: "Male",
    "Last Visit": "27/4/2022",
    Diseases: "typhoid",
    Report: "<PictureAsPdfOutlinedIcon />",
    Details: "",
  },
  {
    "#": patientPic,
    "Patient Name": "John Doe",
    Gender: "Male",
    "Last Visit": "27/4/2022",
    Diseases: "malaria",
    Report: "<PictureAsPdfOutlinedIcon />",
    Details: "",
  },
  {
    "#": patientPic,
    "Patient Name": "John Doe",
    Gender: "Male",
    "Last Visit": "27/4/2022",
    Diseases: "infection",
    Report: "<PictureAsPdfOutlinedIcon />",
    Details: "",
  },
];
